version: '3'
services:
  baidupcs-web:
    image: johngong/baidupcs-web                                 # 镜像`johngong/baidupcs-web`
    container_name: baidupcs-web                                 # 容器名为'baidupcs-web'
    restart: unless-stopped                                              # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    volumes:                                                     # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./baidupcs-web/downloads:/root/Downloads"
      - "./baidupcs-web/config:/config"
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:                              # 映射端口
      - "5299:5299"
