version: '3'
services:
  elasticsearch:
    image: yanliangzhong/elasticsearch6.3.2                   # 镜像`yanliangzhong/elasticsearch6.3.2`
    container_name: elasticsearch                             # 容器名为'elasticsearch'
    restart: unless-stopped                                           # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    environment:                              # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
