version: '3'
services:
  sentinel:
    image: bladex/sentinel-dashboard                             # 镜像`bladex/sentinel-dashboard`
    container_name: sentinel                                     # 容器名为'sentinel'
    restart: always                                              # 指定容器退出后的重启策略为始终重启
    environment:                                                 # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:                                                       # 映射端口
      - "8858:8858"
