version: '3'
services:
  sentinel:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/sentinel-dashboard:1.8.4-nacos
    container_name: sentinel                                     # 容器名为'sentinel'
    restart: unless-stopped                                      # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    environment:                                                 # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      SENTINEL_AUTH_USERNAME: sentinel # sentinel账号
      SENTINEL_AUTH_PASSWORD: sentinel # sentinel密码
      # TODO nacos配置信息
      NACOS_SERVER_ADDR: www.zhengqingya.com:8848    # 注：这里不能为`127.0.0.1`或`localhost`方式！！！
      NACOS_NAMESPACE: prod
      NACOS_GROUP: sentinel-group
      NACOS_USERNAME: nacos
      NACOS_PASSWORD: nacos
    ports:                                                       # 映射端口
      - "8858:8858"
