ARG ELK_VERSION

FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}

# 运行在线插件安装
# RUN elasticsearch-plugin install royrusso/elasticsearch-HQ

# 安装离线插件
# ADD plugins /usr/share/elasticsearch/plugins/
