version: '3'

# 网桥 -> 方便相互通讯
networks:
  mycat:
    driver: bridge

services:
  mycat:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/mycat      # 原镜像`longhronshens/mycat-docker`
    container_name: mycat_server                                  # 容器名为'mycat_server'
    restart: unless-stopped                                       # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    volumes:                                                      # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./mycat/conf/schema.xml:/usr/local/mycat/conf/schema.xml"
      - "./mycat/conf/server.xml:/usr/local/mycat/conf/server.xml"
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:                              # 映射端口
      - "8066:8066"
      - "9066:9066"
    networks:
      - mycat
