apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cm
  labels:
    app: prometheus
data:
  prometheus.yml: |+
    global:
      scrape_interval: 10s
      scrape_timeout: 10s
      evaluation_interval: 10m

    scrape_configs:
      # - job_name: linux
      #   static_configs:
      #     - targets: ['node-exporter:9100']
      #       labels:
      #         instance: localhost
      - job_name: telegraf
        static_configs:
          - targets: ['telegraf-svc:9273']
            labels:
              instance: telegraf
      - job_name: macos-node-exportor
        static_configs:
          - targets: ['10.11.43.78:9100']
            labels:
              instance: macos
